<?php

$arBlog = [
    'post1'=>[
        'title'=>'Made with love in toronto',
        'text'=>'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sit dignissimos fuga totam nemo nulla officia sunt voluptates ipsa aliquam adipisci amet culpa ratione accusantium possimus animi nobis modi dolores, tempora enim! Rem doloremque rerum aperiam quaerat nisi repellat totam, tempora officia dignissimos quos dolore error quibusdam assumenda quasi ad qui est sit ullam quidem voluptate expedita maiores explicabo accusantium sint! Soluta officia, eaque praesentium eveniet assumenda dolore laborum voluptatem veritatis ut blanditiis porro consequatur maiores at aperiam natus sapiente quis molestias nisi. Fugit laudantium iste facere dolor, voluptatibus fugiat facilis, sint amet eum accusamus alias provident explicabo eius. Cum quam ut quisquam voluptates ex dolorem rem sunt eius quasi deserunt, tempora necessitatibus, mollitia eveniet hic eligendi minima, error officia voluptate eum! Delectus explicabo hic, rerum fuga earum vel saepe, aspernatur ipsa soluta aliquam sed expedita ullam voluptatibus ipsam. Ad quis fuga eius totam officia tempore aspernatur corrupti facere saepe nam iure tempora magni voluptate, vero at, molestiae amet commodi harum nobis? Iusto, delectus in repudiandae adipisci quod fugit at, iste error provident ad doloremque eius eos! Dolores, sequi hic officia saepe animi architecto eaque dolorum culpa ut repellat in facilis odio voluptates corporis consectetur ipsum omnis asperiores quia a unde!'
    ],
    'post2'=>[
        'title'=>'Startup news & emerging tech',
        'text'=>'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sit dignissimos fuga totam nemo nulla officia sunt voluptates ipsa aliquam adipisci amet culpa ratione accusantium possimus animi nobis modi dolores, tempora enim! Rem doloremque rerum aperiam quaerat nisi repellat totam, tempora officia dignissimos quos dolore error quibusdam assumenda quasi ad qui est sit ullam quidem voluptate expedita maiores explicabo accusantium sint! Soluta officia, eaque praesentium eveniet assumenda dolore laborum voluptatem veritatis ut blanditiis porro consequatur maiores at aperiam natus sapiente quis molestias nisi. Fugit laudantium iste facere dolor, voluptatibus fugiat facilis, sint amet eum accusamus alias provident explicabo eius. Cum quam ut quisquam voluptates ex dolorem rem sunt eius quasi deserunt, tempora necessitatibus, mollitia eveniet hic eligendi minima, error officia voluptate eum! Delectus explicabo hic, rerum fuga earum vel saepe, aspernatur ipsa soluta aliquam sed expedita ullam voluptatibus ipsam. Ad quis fuga eius totam officia tempore aspernatur corrupti facere saepe nam iure tempora magni voluptate, vero at, molestiae amet commodi harum nobis? Iusto, delectus in repudiandae adipisci quod fugit at, iste error provident ad doloremque eius eos! Dolores, sequi hic officia saepe animi architecto eaque dolorum culpa ut repellat in facilis odio voluptates corporis consectetur ipsum omnis asperiores quia a unde!'
    ],
    'post3'=>[
        'title'=>'Bitcoin will soon rule the world',
        'text'=>'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sit dignissimos fuga totam nemo nulla officia sunt voluptates ipsa aliquam adipisci amet culpa ratione accusantium possimus animi nobis modi dolores, tempora enim! Rem doloremque rerum aperiam quaerat nisi repellat totam, tempora officia dignissimos quos dolore error quibusdam assumenda quasi ad qui est sit ullam quidem voluptate expedita maiores explicabo accusantium sint! Soluta officia, eaque praesentium eveniet assumenda dolore laborum voluptatem veritatis ut blanditiis porro consequatur maiores at aperiam natus sapiente quis molestias nisi. Fugit laudantium iste facere dolor, voluptatibus fugiat facilis, sint amet eum accusamus alias provident explicabo eius. Cum quam ut quisquam voluptates ex dolorem rem sunt eius quasi deserunt, tempora necessitatibus, mollitia eveniet hic eligendi minima, error officia voluptate eum! Delectus explicabo hic, rerum fuga earum vel saepe, aspernatur ipsa soluta aliquam sed expedita ullam voluptatibus ipsam. Ad quis fuga eius totam officia tempore aspernatur corrupti facere saepe nam iure tempora magni voluptate, vero at, molestiae amet commodi harum nobis? Iusto, delectus in repudiandae adipisci quod fugit at, iste error provident ad doloremque eius eos! Dolores, sequi hic officia saepe animi architecto eaque dolorum culpa ut repellat in facilis odio voluptates corporis consectetur ipsum omnis asperiores quia a unde!'
    ],
    'post4'=>[
        'title'=>'Wearable technology on the rise',
        'text'=>'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sit dignissimos fuga totam nemo nulla officia sunt voluptates ipsa aliquam adipisci amet culpa ratione accusantium possimus animi nobis modi dolores, tempora enim! Rem doloremque rerum aperiam quaerat nisi repellat totam, tempora officia dignissimos quos dolore error quibusdam assumenda quasi ad qui est sit ullam quidem voluptate expedita maiores explicabo accusantium sint! Soluta officia, eaque praesentium eveniet assumenda dolore laborum voluptatem veritatis ut blanditiis porro consequatur maiores at aperiam natus sapiente quis molestias nisi. Fugit laudantium iste facere dolor, voluptatibus fugiat facilis, sint amet eum accusamus alias provident explicabo eius. Cum quam ut quisquam voluptates ex dolorem rem sunt eius quasi deserunt, tempora necessitatibus, mollitia eveniet hic eligendi minima, error officia voluptate eum! Delectus explicabo hic, rerum fuga earum vel saepe, aspernatur ipsa soluta aliquam sed expedita ullam voluptatibus ipsam. Ad quis fuga eius totam officia tempore aspernatur corrupti facere saepe nam iure tempora magni voluptate, vero at, molestiae amet commodi harum nobis? Iusto, delectus in repudiandae adipisci quod fugit at, iste error provident ad doloremque eius eos! Dolores, sequi hic officia saepe animi architecto eaque dolorum culpa ut repellat in facilis odio voluptates corporis consectetur ipsum omnis asperiores quia a unde!'
    ],
    'post5'=>[
        'title'=>'Learn web design in 30 days',
        'text'=>'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sit dignissimos fuga totam nemo nulla officia sunt voluptates ipsa aliquam adipisci amet culpa ratione accusantium possimus animi nobis modi dolores, tempora enim! Rem doloremque rerum aperiam quaerat nisi repellat totam, tempora officia dignissimos quos dolore error quibusdam assumenda quasi ad qui est sit ullam quidem voluptate expedita maiores explicabo accusantium sint! Soluta officia, eaque praesentium eveniet assumenda dolore laborum voluptatem veritatis ut blanditiis porro consequatur maiores at aperiam natus sapiente quis molestias nisi. Fugit laudantium iste facere dolor, voluptatibus fugiat facilis, sint amet eum accusamus alias provident explicabo eius. Cum quam ut quisquam voluptates ex dolorem rem sunt eius quasi deserunt, tempora necessitatibus, mollitia eveniet hic eligendi minima, error officia voluptate eum! Delectus explicabo hic, rerum fuga earum vel saepe, aspernatur ipsa soluta aliquam sed expedita ullam voluptatibus ipsam. Ad quis fuga eius totam officia tempore aspernatur corrupti facere saepe nam iure tempora magni voluptate, vero at, molestiae amet commodi harum nobis? Iusto, delectus in repudiandae adipisci quod fugit at, iste error provident ad doloremque eius eos! Dolores, sequi hic officia saepe animi architecto eaque dolorum culpa ut repellat in facilis odio voluptates corporis consectetur ipsum omnis asperiores quia a unde!'
    ]
];

$arMenu = [
    'Home' => "/",
    'About' => './about/index.php',
    'Blog' => './blog/index.php',
    'Portfolio' => './portfolio/index.php',
    'Contacts' => './contacts/index.php'
]

?>
